'use strict';

const TIMER = { NONE: 'none', SHORT: 'short', LONG: 'long' };

const PACKS = [
    {
        id: 'toms-birthday-2025',
        name: "Tom's Birthday 2025",
        description: "Custom pub crawl pack for Tom's birthday",
        headerTitle: "Tom's Birthday",
        permanentRules: [
            "Draw one card for each hour you arrive late",
            "If Black Eyed Peas plays at any point, everyone must finish their drink",
            "If you do a poo, the group guesses the colour. Everyone but the winner must draw a card",
            "If you do not want to carry out a forfeit, once per game you may use the Hudson Paw to wish for a different forfeit."
        ],
        drawRules: [
            { text: "Tom tells you to draw a card — his word is final",                  pub: 1 },
            { text: "Use any player's first name, nickname, or abbreviated name",         pub: 1 },
            { text: "Fail to split the G",                                               pub: 2 },
            { text: "Place your drink within a thumb's length of the table",             pub: 2 },
            { text: "Take a piss at the pub (first piss per pub is free)",               pub: 3 },
            { text: "If you are the only one outside the pub at any point",              pub: 3 },
            { text: "Drink with your right hand",                                        pub: 4 },
            { text: "Accidentally rhyme",                                                pub: 4 }
        ],
        othersDrawRules: [
            { text: "When leaving a pub, you have the best placed Matt/Ellen slander sticker",  pub: 1 },
            { text: "Drink a full glass of milk",                                               pub: 1 },
            { text: "Manage to split the G",                                                    pub: 2 },
            { text: "Challenge and win a boat race",                                            pub: 2 },
            { text: "Buy Tom a shot",                                                           pub: 3 },
            { text: "Eat a dog treat (Once per pub)",                                           pub: 3 },
            { text: "Wear the gamer vest for a whole pub",                                      pub: 4 },
        ],
        cards: [
            { number: 1,  timer: TIMER.NONE,  title: "Back at BCOT",                          text: "Tom used to love his white chocolate Starbucks at college. Your next drink must be coffee based" },
            { number: 2,  timer: TIMER.NONE,  title: "Short Shorts",                          text: "Tom wore his tight chino shorts out and has ripped them, revealing his bussy. Poke him in the arse quick!" },
            { number: 3,  timer: TIMER.NONE,  title: "Pummel Party",                          text: "You picked up an Arcade Challenge! Challenge someone to a game of 'Crappy Turd', highest score across 3 attempts. Loser takes 5 sips. Access the game here: https://jojomohojo.itch.io/crappy-turd" },
            { number: 4,  timer: TIMER.NONE,  title: "Sussy ChigBungus",                      text: "Hudson just got voted in as Reform's new leader. Ask him to record a Nigel Farage style Cameo, Tom gets to choose who it's sent to" },
            { number: 5,  timer: TIMER.NONE,  title: "Here's My Spout",                       text: "Top up the drink with the least left using your own, acting like a teapot" },
            { number: 6,  timer: TIMER.NONE,  title: "Bring out your Scrap!",                 text: "If you have any loose change, use it to enact 'Save the Queen' on unsuspecting victims" },
            { number: 7,  timer: TIMER.NONE,  title: "Super Smash Bros.",                     text: "It's a game of categories, but the only category allowed is Super Smash Bros characters, you start. Loser takes 3 sips" },
            { number: 8,  timer: TIMER.NONE,  title: "Packing Game",                          text: "Host a round of the packing game. Last to guess the rule must take 5 sips" },
            { number: 9,  timer: TIMER.NONE,  title: "Soaking Wet",                           text: "Grippin' and fartin' and grippin' and huggin' got dat dookie hole soaking wet, soaking wet. Neck a pint of water in one go or take a shot" },
            { number: 10, timer: TIMER.NONE,  title: "Big Man's Choice",                      text: "You and Tom decide the next drink everyone has to order at the next pub" },
            { number: 11, timer: TIMER.NONE,  title: "Tom's Favourite Meme",                  text: "Keep your toddlers on a leash! Go ask for 'The Pitbull of Drinks' at the bar and enjoy it" },
            { number: 12, timer: TIMER.NONE,  title: "Buzzballs",                             text: "Buzzballs" },
            { number: 13, timer: TIMER.NONE,  title: "In the Doghouse",                       text: "You've drank too much and are snoring loudly. Hannah is making you sleep on the sofa tonight. You have to finish your drink at a table by yourself" },
            { number: 14, timer: TIMER.NONE,  title: "Drink for the Fallen",                  text: "Take a drink for each person who has gone home. If no one has left yet, down your drink as a toast in advance" },
            { number: 15, timer: TIMER.NONE,  title: "Liam's Round",                          text: "Liam is buying your next drink but has forgotten your order. Drink whatever he brings back for you. (Liam doesn't actually have to pay for you)" },
            { number: 16, timer: TIMER.NONE,  title: "Hannah's Quiz Time",                    text: "Hannah asks you a question about Tom. If you get it wrong, and someone else answers correctly, take 3 sips" },
            { number: 17, timer: TIMER.LONG,  timerSeconds: 300, timerLabel: "5 Min Ug Rule",    title: "Hat of Ug",                              text: "You can only talk in one syllable words for five minutes. Each time you fail, take two sips" },
            { number: 18, timer: TIMER.LONG,  timerSeconds: 300, timerLabel: "5 Min Heaven Rule", title: "Tom wishes he was dead, show him the way", text: "For the next 5 minutes, any time you point to heaven — Tom's dream — everyone else must point too. The last one to point takes 3 sips" },
            { number: 19, timer: TIMER.SHORT, timerSeconds: 15,  title: "Who's That Pokémon?",    text: "Tom tells you three pokemon names, but one of them is false. You must guess the false one within 15 seconds, or Tom will draw it on your arm in sharpie" },
            { number: 20, timer: TIMER.NONE,  title: "Back in Action",                        text: "Just like Tom, your legs are now stronger than ever! Choose someone to carry back to the train. They cannot have been picked before" },
            { number: 21, timer: TIMER.SHORT, timerSeconds: 15,  title: "Absolute Bullshit",  text: "It's time for a Mario Party mini-game! Give your best impression of a Mario Party character and Tom has to guess. If Tom can't guess correctly within 15 seconds, you must both take 3 sips" },
            { number: 22, timer: TIMER.NONE,  title: "Blind Man and Dog",                     text: "You are now blind. Choose a guide dog to guide you while you are blindfolded until the next pub" },
            { number: 23, timer: TIMER.NONE,  title: "Pokémon Trivia",                        text: "Ask Tom a question about Pokémon — feel free to google one. If he gets it right, you have to buy him his favourite drink. If he gets it wrong, you can buy him any drink" },
            { number: 24, timer: TIMER.NONE,  title: "Monttttyyyyyy!",                        text: "Monty burnt a penis into the roof of Tom's car, now he's drawing one on you. Let Monty — or Tom if he's not present — draw a penis in sharpie onto an exposed part of your body" },
            { number: 25, timer: TIMER.NONE,  title: "The Classic Attire",                    text: "He never leaves the house without it. You have to wear Tom's hawaiian shirt until this card is next drawn. Or take a shot of spirit." },
            { number: 26, timer: TIMER.NONE,  title: "God of Would you Rather?",              text: "Video call Hudson and tell him a 'Would you rather?'. If he doesn't approve, take 5 sips." },
            { number: 27, timer: TIMER.LONG,  timerSeconds: 300, timerLabel: "5 Min Eyes Rule",  title: "Sleeping with Both Eyes Open", text: "You drank so much last night you slept with your eyes open, now they're all sticky and bloodshot. Anyone who looks you in the eyes for the next 5 minutes must take 2 sips" },
            { number: 28, timer: TIMER.NONE,  title: "Follow that tune!",                     text: "Do the Gym Skin dance to the music currently playing. If there is none, go follow that tune and boogie!" },
            { number: 29, timer: TIMER.NONE,  title: "Horses Don't Have Hands!",              text: "You is a horse. Horses don't have hands. Let Tom feed you the rest of your drink" },
            { number: 30, timer: TIMER.NONE,  title: "Anti-Clavicular",                       text: "Challenge someone to an anti-mog on mogging.com. Whoever gets the higher score loses and has to drink half a drink's worth" },
            { number: 31, timer: TIMER.NONE,  title: "It's not 11 o'clock yet!",              text: "Tom is still working overtime and can't drink. Everyone down his drink for him so he can focus on work" },
            { number: 32, timer: TIMER.NONE,  title: "Chance Time!",                          text: "You landed on a Chance Time space. Swap everyone's drinks around — you choose who gets what" },
            { number: 33, timer: TIMER.NONE,  title: "Strong Bones!",                         text: "Don't end up like Tom with rickets. Drink a glass of milk, and you must finish it before you can return to your drink" },
            { number: 34, timer: TIMER.NONE,  title: "Butt Text, Sorry!",                     text: "Tom sat on your phone and somehow managed to send a text on it. Tom is allowed to send one text to anyone on your phone — excluding work and parents. If you refuse, down your drink" },
            { number: 35, timer: TIMER.NONE,  title: "Avid Gamer Moment",                     text: "You are an avid gamer. You must wear Ellen's gamer shirt until someone else draws this card or decides to wear it themselves. If you refuse, take a shot of spirit" },
            { number: 36, timer: TIMER.NONE,  title: "Well That's Written Off...",            text: "Tom just hit ANOTHER deer on the road and now his car is totalled. Buy Tom a drink since he's skint from car repairs" },
            { number: 37, timer: TIMER.NONE,  title: "Last Orders",                           text: "The bar just rang the bell! If anyone has a third or less of drink left in their glass, they have to finish it off" },
            { number: 38, timer: TIMER.NONE,  title: "JANKENPON!",                            text: "Challenge someone to Rock, Paper, Scissors. Best of 3. Loser downs their drink" },
            { number: 39, timer: TIMER.NONE,  title: "Guitar Hero Pro",                       text: "Tom loves to belt out some tunes on the Wii. Let the group record a new ringtone for you and leave your phone on loudspeaker for the rest of the night — or take a shot of spirit" },
            { number: 40, timer: TIMER.LONG,  timerSeconds: 300, timerLabel: "5 Min Charlie Kirk Rule", title: "We are Charlie Kirk!", text: "We carrrry the flame! You must end every sentence with 'We are Charlie Kirk' for the next 5 minutes. Each time you forget, take 2 sips" },
            { number: 41, timer: TIMER.NONE,  title: "Bing Chilling",                         text: "Order a pint of Chinese guinness from the bar" },
            { number: 42, timer: TIMER.SHORT, timerSeconds: 120, title: "LET THEM COOK!",     text: "Hold up, let them cook. Come up with an unpopular opinion/conspiracy, you have 2 minutes to convince the table to your side. Take a sip for each player you are unable to win over." },
            { number: 43, timer: TIMER.SHORT, timerSeconds: 120, title: "Would You Rather? — Redux", text: "A good 'Would you rather' could unite even Israel and Palestine. You have 2 minutes to come up with one for the table. After everyone answers, take the totals of each side and drink the difference." },
            { number: 44, timer: TIMER.SHORT, timerSeconds: 60,  title: "Charades",           text: "A good ol' fashioned round of charades. Someone must guess within 60 seconds, or else take 3 sips. If guessed, both players give out two sips" },
            { number: 45, timer: TIMER.NONE,  title: "Paul Hudson, Wingman Extraordinaire",   text: "You've spotted someone interesting in the pub and desperately want to know more about them. Call Hudson and let him give you a question to ask the stranger. If you refuse, take a shot of spirit" },
            { number: 46, timer: TIMER.NONE,  title: "Your Biggest Fan",                      text: "You've noticed one of your all time idols is working behind the bar. You can't pass up the opportunity, go get a selfie with them!" },
            { number: 47, timer: TIMER.NONE,  title: "Go straight to jail",                   text: "Tom's traveller background has caught up with him and you. You must be handcuffed together until the next pub" },
            { number: 48, timer: TIMER.SHORT, timerSeconds: 60,  title: "Pub Quiz Wildcard",  text: "Someone picks any subject, you have 60 seconds to name as many things in that category as possible. Under 10? Take a sip for each you were short", ai: true },
            { number: 49, timer: TIMER.SHORT, timerSeconds: 30,  title: "Name That Banger",   text: "Hum the first song that comes to mind. The table has 30 seconds to guess it. If no one gets it, everyone has 3 sips", ai: true },
            { number: 50, timer: TIMER.NONE,  title: "Speed Round",                           text: "You and the person to your left simultaneously describe each other in one word to the group. If the table agrees yours is more accurate, they take 3 sips. If theirs is, you do", ai: true },
            { number: 51, timer: TIMER.LONG,  timerSeconds: 300, timerLabel: "5 Min Accent Rule", title: "Gap Yah", text: "Tom once considered doing a gap year to 'find himself'. For the next 5 minutes you must speak in a posh gap year accent. Every time you break character, take 2 sips", ai: true },
            { number: 52, timer: TIMER.SHORT, timerSeconds: 30,  title: "Invisible Pint",     text: "Mime drinking a pint as realistically as possible. The table votes — if less than half believe you, you have to drink the real thing in the same time you mimed it", ai: true },
        ]
    }
];
